### ISSUE TITLE
Allow root to be a folder

### ISSUE THREAD

**Issue by mavrothal** [dimkr/frugalify#5]
In frugalified puppies vmlinuz, ucode.cpio and frugalify can be anywhere and their location can be defined by the bootloader and the kernel cml. However, upper and all SFSs must be at the root of PARTUUID.
Would be handy if the SFSs/upper location could be bootloader defined, or simply accept the frugalify location as root and look only there.
This way frugalified pups could be more flexible and be installed together with other PUPs/OSs in the same partition.

PS: Labels are not active in this repo so I can not label this issue as "Enhancement"

**Comment by dimkr** [comment]
This issue should be at https://github.com/puppylinux-woof-CE/frugalify, somehow I forgot to delete this fork
